export const provincias = [
    { label: 'Álava', value: 'alava' },
    { label: 'Albacete', value: 'albacete' },
    { label: 'Alicante', value: 'alicante' },
    { label: 'Almería', value: 'almeria' },
    { label: 'Asturias', value: 'asturias' },
    { label: 'Ávila', value: 'avila' },
    { label: 'Badajoz', value: 'badajoz' },
    { label: 'Baleares', value: 'baleares' },
    { label: 'Barcelona', value: 'barcelona' },
    { label: 'Burgos', value: 'burgos' },
    { label: 'Cáceres', value: 'caceres' },
    { label: 'Cádiz', value: 'cadiz' },
    { label: 'Cantabria', value: 'cantabria' },
    { label: 'Castellón', value: 'castellon' },
    { label: 'Ciudad Real', value: 'ciudad_real' },
    { label: 'Córdoba', value: 'cordoba' },
    { label: 'Cuenca', value: 'cuenca' },
    { label: 'Girona', value: 'girona' },
    { label: 'Granada', value: 'granada' },
    { label: 'Guadalajara', value: 'guadalajara' },
    { label: 'Guipúzcoa', value: 'guipuzcoa' },
    { label: 'Huelva', value: 'huelva' },
    { label: 'Huesca', value: 'huesca' },
    { label: 'Jaén', value: 'jaen' },
    { label: 'La Coruña', value: 'la_coruna' },
    { label: 'La Rioja', value: 'la_rioja' },
    { label: 'Las Palmas', value: 'las_palmas' },
    { label: 'León', value: 'leon' },
    { label: 'Lleida', value: 'lleida' },
    { label: 'Lugo', value: 'lugo' },
    { label: 'Madrid', value: 'madrid' },
    { label: 'Málaga', value: 'malaga' },
    { label: 'Murcia', value: 'murcia' },
    { label: 'Navarra', value: 'navarra' },
    { label: 'Ourense', value: 'ourense' },
    { label: 'Palencia', value: 'palencia' },
    { label: 'Pontevedra', value: 'pontevedra' },
    { label: 'Salamanca', value: 'salamanca' },
    { label: 'Santa Cruz de Tenerife', value: 'santa_cruz_de_tenerife' },
    { label: 'Segovia', value: 'segovia' },
    { label: 'Sevilla', value: 'sevilla' },
    { label: 'Soria', value: 'soria' },
    { label: 'Tarragona', value: 'tarragona' },
    { label: 'Teruel', value: 'teruel' },
    { label: 'Toledo', value: 'toledo' },
    { label: 'Valencia', value: 'valencia' },
    { label: 'Valladolid', value: 'valladolid' },
    { label: 'Vizcaya', value: 'vizcaya' },
    { label: 'Zamora', value: 'zamora' },
    { label: 'Zaragoza', value: 'zaragoza' }
  ];
  